name: Sync Repository Data to Metastore

on:
  workflow_dispatch:
  push:
    paths:
      - 'workflow/**'

jobs:
  sync_to_metastore:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repo
        uses: actions/checkout@v2

      - name: Detect Changes in the Specific Directory
        id: file_changes
        run: |
          # Use git to check for changes in the specific directory
          if git diff --name-only ${{ github.event.before }} ${{ github.sha }} -- 'your-specific-directory/'
          then
            echo "::set-output name=changes_detected::true"
          fi

      - name: Push to Metastore
        if: steps.file_changes.outputs.changes_detected == 'true'
        run: |
          # Configure git
          git config --global user.email "cdasmkt@gmail.com"
          git config --global user.name "Your Bot Name"

          # Clone the metastore repository
          git clone https://github.com/Cdaprod/cda.metastore.git
          cd cda.metastore

          # Copy the updated data
          cp -R ../your-specific-directory/* ./path-to-metastore-directory/

          # Commit and push the changes
          git add .
          git commit -m "Update metastore with latest repo data"
          git push

        env:
          GITHUB_TOKEN: ${{ secrets.YOUR_GITHUB_TOKEN }}